### ISSUE TITLE
Obter balanço da conta no TradeOgre

### ISSUE THREAD

**Issue by taisprestes01** [taisprestes01/Coinfolio#4]
**Utilize a branch https://github.com/taisprestes01/Coinfolio/tree/Feature/getBalance**
- [x] Criar conta no trade ogre
- [x] Criar nova pagina chamada "Wallet.js" em assets/js/
- [x] Criar função em Wallet.js para chamar o endPoint "Get Balance" da API https://tradeogre.com/help/api
![image](https://github.com/taisprestes01/Coinfolio/assets/108246691/6125b0bb-4438-4ca0-8c0b-76f28af70c6b)

**Comment by Guilsrs** [comment]
Finalizado no dia 20/04/2024.
